obstacle_range: 2.5
raytrace_range: 3.0

#footprint: [[-0.35, -0.3], [-0.35, 0.3], [0.35, 0.3], [0.35, -0.3]]
robot_radius: 0.25

inflation_radius: 0.6
cost_scaling_factor: 4.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: odin1_base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}


