GlobalPlanner:
  allow_unknown: false  # false: do not go to the unknown area
  default_tolerance: 0.3
  visualize_potential: false
  use_dijkstra: false
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 66
  cost_factor: 0.55
  publish_potential: true
  orientation_mode: 0
  orientation_window_size: 1

